[package]
name = "evmc-declare"
version = "0.1.0"
authors = ["Jake Lang <jak3lang@gmail.com>"]
edition = "2018"

[dependencies]
quote = "0.6.12"
heck = "0.3.1"
proc-macro2 = "0.4.29"

[dependencies.syn]
version = "0.15.33"
features = ["full"]

[lib]
proc-macro = true
