[package]
name = "evmc-declare-tests"
version = "0.1.0"
authors = ["Jake Lang <jak3lang@gmail.com>"]
edition = "2018"

[dependencies]
evmc-declare = { path = "../evmc-declare" }
evmc-sys = { path = "../evmc-sys" }
evmc-vm = { path = "../evmc-vm" }
